### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joroKr21** [ChristopherDavenport/scalaz-task-effect#13]
I would like to use it but I need to know what the license is :smile:

**Comment by ChristopherDavenport** [comment]
My apologies, it is MIT. I will get it up asap.

**Comment by ChristopherDavenport** [comment]
To make clear I am not modifying what was already in place. This was indicated in the build which is why this can be meaningfully released to cetral. 

https://github.com/ChristopherDavenport/scalaz-task-effect/blob/master/build.sbt#L90

However I agree this was an oversight to not include the file.

**Comment by joroKr21** [comment]
Thank you :+1:
